name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      working-directory: ./MultiConverterGUI
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MultiConverter_${{ steps.tag_version.outputs.new_tag }}
        path: .\MultiConverterGUI\bin\Release\net5.0-windows\win-x64\publish

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

    - uses: actions/download-artifact@v3
      with:
        name: MultiConverter_${{ steps.tag_version.outputs.new_tag }}
        
    - name: Display structure of downloaded files
      run: ls -R
        
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
       GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: D:\a\MultiConverter\MultiConverter\MultiConverter_${{ steps.tag_version.outputs.new_tag }}.zip
        asset_name: MultiConverter_${{ steps.tag_version.outputs.new_tag }}.zip
        asset_content_type: application/zip
        
